export const heroNotes = [
  {
    label: 'Mais fruta, menos excesso',
    description: '20 receitas para beber melhor todos os dias',
    target: 'cardapio',
    category: 'todos',
    rotation: -2.5,
  },
  {
    label: 'Citricos do amanhecer',
    description: 'laranja, limao, maracuja e brilho gelado',
    target: 'cardapio',
    category: 'citricos',
    rotation: 2.25,
  },
  {
    label: 'Roses para a vontade de doce',
    description: 'melancia, pitaya e hibisco bem servidos',
    target: 'cardapio',
    category: 'roses',
    rotation: -1.75,
  },
  {
    label: 'Verdes do jardim',
    description: 'horta fria, pepino e folhas frescas',
    target: 'cardapio',
    category: 'verdes',
    rotation: 2.8,
  },
]

export const categories = [
  {
    id: 'citricos',
    kicker: 'Menu 01',
    label: 'Citricos Luminosos',
    description:
      'Laranjas, maracuja, limao e abacaxi em receitas com brilho, acidez limpa e final refrescante.',
    rotation: -1.8,
    cardBackground:
      'linear-gradient(180deg, rgba(255, 246, 225, 0.96), rgba(245, 225, 191, 0.94))',
  },
  {
    id: 'verdes',
    kicker: 'Menu 02',
    label: 'Verdes do Jardim',
    description:
      'Copos herbais com pepino, couve, kiwi, hortela e folhas que trazem a sensacao de horta fresca.',
    rotation: 1.6,
    cardBackground:
      'linear-gradient(180deg, rgba(245, 248, 240, 0.96), rgba(221, 232, 210, 0.95))',
  },
  {
    id: 'tropicais',
    kicker: 'Menu 03',
    label: 'Tropicais Aveludados',
    description:
      'Texturas mais cremosas com manga, coco, caju, papaia e goiaba para um final de tarde expansivo.',
    rotation: -1.2,
    cardBackground:
      'linear-gradient(180deg, rgba(255, 243, 236, 0.96), rgba(243, 217, 194, 0.95))',
  },
  {
    id: 'roses',
    kicker: 'Menu 04',
    label: 'Roses Gelados',
    description:
      'Melancia, pitaya, morango, hibisco e beterraba em receitas mais perfumadas e cenicas.',
    rotation: 1.85,
    cardBackground:
      'linear-gradient(180deg, rgba(252, 242, 240, 0.96), rgba(244, 219, 220, 0.95))',
  },
]

export const sceneChapters = [
  {
    id: 'mesa-solar',
    kicker: 'Capitulo 01',
    title: 'Mesa Solar',
    description:
      'Receitas citricas para abrir a manha com fruta fresca, acidez limpa e mais leveza no primeiro copo.',
    overlay:
      'Laranja, manga, maracuja e limao entram como convite para trocar excesso por fruta de verdade.',
    meta: 'Mais brilho no copo, menos peso na rotina.',
    category: 'citricos',
    imageKey: 'hero',
    imagePosition: '50% 50%',
    alt: 'Frutas compondo o nome Sucos Vivos sobre fundo de papel claro',
    ingredients: ['manga', 'laranja', 'kiwi', 'coco'],
    canvas:
      'linear-gradient(180deg, rgba(255, 249, 241, 0.98), rgba(248, 235, 211, 0.98))',
    border: 'rgba(226, 198, 156, 0.8)',
    noteSurface: 'rgba(255, 248, 235, 0.9)',
  },
  {
    id: 'jardim-fluido',
    kicker: 'Capitulo 02',
    title: 'Jardim Fluido',
    description:
      'Verdes frios com folhas, pepino e frutas claras para refrescar a rotina e deixar o paladar mais limpo.',
    overlay:
      'Os verdes entram para quem busca frescor, horta e um copo que combina com dias mais leves.',
    meta: 'Herbal, gelado e muito fresco.',
    category: 'verdes',
    imageKey: 'drinks',
    imagePosition: '68% 34%',
    alt: 'Copos de sucos naturais com folhas verdes e frutas tropicais em cima de papel',
    ingredients: ['pepino', 'hortela', 'couve', 'uva verde'],
    canvas:
      'linear-gradient(180deg, rgba(241, 246, 237, 0.98), rgba(220, 230, 212, 0.98))',
    border: 'rgba(164, 182, 151, 0.8)',
    noteSurface: 'rgba(239, 245, 232, 0.92)',
  },
  {
    id: 'rosa-em-cena',
    kicker: 'Capitulo 03',
    title: 'Rosa em Cena',
    description:
      'Sucos rosados para quando bate a vontade de doce, mas o corpo pede fruta, agua e leveza.',
    overlay:
      'Melancia, pitaya, morango e hibisco deixam a mesa bonita e o sabor mais delicado.',
    meta: 'Doce natural com cara de ritual bonito.',
    category: 'roses',
    imageKey: 'drinks',
    imagePosition: '36% 62%',
    alt: 'Suco rosado em composicao editorial com frutas e papeles sobre a mesa',
    ingredients: ['melancia', 'pitaya', 'hibisco', 'morango'],
    canvas:
      'linear-gradient(180deg, rgba(253, 244, 243, 0.98), rgba(244, 219, 218, 0.98))',
    border: 'rgba(222, 176, 181, 0.84)',
    noteSurface: 'rgba(252, 244, 242, 0.92)',
  },
  {
    id: 'tropico-lento',
    kicker: 'Capitulo 04',
    title: 'Tropico Lento',
    description:
      'Misturas tropicais mais cremosas para a fome da tarde, com fruta, coco e textura macia.',
    overlay:
      'Manga, goiaba, caju e abacaxi deixam o final do menu mais quente, redondo e convidativo.',
    meta: 'Mais corpo, sem perder o frescor.',
    category: 'tropicais',
    imageKey: 'drinks',
    imagePosition: '76% 72%',
    alt: 'Sucos tropicais cremosos com manga e abacaxi em enquadramento editorial',
    ingredients: ['manga', 'coco', 'goiaba', 'abacaxi'],
    canvas:
      'linear-gradient(180deg, rgba(255, 246, 239, 0.98), rgba(242, 219, 196, 0.98))',
    border: 'rgba(218, 179, 150, 0.84)',
    noteSurface: 'rgba(255, 246, 240, 0.92)',
  },
]

export const recipes = [
  {
    id: 'clarao-de-laranja',
    category: 'citricos',
    name: 'Clarao de Laranja',
    note: 'Laranja pera, cenoura, maracuja e gelo batido.',
    ingredients: ['300 ml de suco de laranja', '1 cenoura pequena', 'polpa de 1 maracuja', 'gelo a gosto'],
    method:
      'Bata tudo rapidamente ate ficar liso. Sirva logo em seguida para manter o brilho citrico e a textura fresca.',
    profile: 'Doce citrico com final vivo.',
    bestMoment: 'Perfeito para a primeira metade da manha.',
    pairing: 'Combina com torrada de fermentacao natural e ricota leve.',
    serve: '300 ml',
    tilt: -1.4,
  },
  {
    id: 'brisa-de-maracuja',
    category: 'citricos',
    name: 'Brisa de Maracuja',
    note: 'Maracuja fresco, agua de coco e hortela macia.',
    ingredients: ['polpa de 2 maracujas', '200 ml de agua de coco', '6 folhas de hortela', 'cubos de gelo'],
    method:
      'Bata a polpa com a agua de coco, coe se quiser e finalize com hortela apenas pulsando para nao amargar.',
    profile: 'Acidez tropical com perfume herbal.',
    bestMoment: 'Fica lindo como pausa gelada no meio da tarde.',
    pairing: 'Vai muito bem com bolo simples de iogurte.',
    serve: '280 ml',
    tilt: 1.2,
  },
  {
    id: 'capim-e-abacaxi',
    category: 'citricos',
    name: 'Capim & Abacaxi',
    note: 'Abacaxi dourado, capim-santo e limao espremido.',
    ingredients: ['2 fatias de abacaxi', '120 ml de infusao fria de capim-santo', 'suco de 1 limao', 'gelo'],
    method:
      'Prepare a infusao, deixe gelar e bata com o abacaxi e o limao. Sirva em copo baixo com bastante gelo.',
    profile: 'Fresco, aromatico e muito limpo.',
    bestMoment: 'Ideal para dias quentes e almocos ao ar livre.',
    pairing: 'Combina com salada de folhas e queijo branco.',
    serve: '320 ml',
    tilt: -0.9,
  },
  {
    id: 'limao-do-pomar',
    category: 'citricos',
    name: 'Limao do Pomar',
    note: 'Limao tahiti, melao claro e um toque de gengibre.',
    ingredients: ['suco de 2 limoes', '1 xicara de melao picado', '1 fatia fina de gengibre', 'agua gelada'],
    method:
      'Bata o melao com o gengibre e complete com o suco de limao e um pouco de agua gelada para alongar o copo.',
    profile: 'Leve, brilhante e com final picante.',
    bestMoment: 'Funciona como entrada refrescante para o jantar.',
    pairing: 'Boa companhia para ceviche vegetal ou peixe grelhado.',
    serve: '290 ml',
    tilt: 1.1,
  },
  {
    id: 'tangerina-dourada',
    category: 'citricos',
    name: 'Tangerina Dourada',
    note: 'Tangerina, maca amarela e curcuma suave.',
    ingredients: ['3 tangerinas', '1 maca amarela', '1 pitada de curcuma', 'gelo quebrado'],
    method:
      'Extraia o suco das tangerinas, bata com a maca e adicione apenas uma ponta de curcuma para tingir e perfumar.',
    profile: 'Aveludado e solar ao mesmo tempo.',
    bestMoment: 'Muito bom para brunch ou fim de tarde ensolarado.',
    pairing: 'Fica lindo com croissant amanteigado.',
    serve: '300 ml',
    tilt: -1.5,
  },
  {
    id: 'jardim-verde',
    category: 'verdes',
    name: 'Jardim Verde',
    note: 'Couve, maca verde, limao e agua de coco.',
    ingredients: ['1 folha de couve', '1 maca verde', 'suco de 1 limao', '180 ml de agua de coco'],
    method:
      'Bata tudo ate a mistura ficar homogenea. Se preferir mais sedoso, coe antes de servir.',
    profile: 'Verde vivo, seco e muito refrescante.',
    bestMoment: 'Uma boa abertura para manhas quentes.',
    pairing: 'Combina com pao integral e queijo minas fresco.',
    serve: '300 ml',
    tilt: 1.3,
  },
  {
    id: 'kiwi-de-verao',
    category: 'verdes',
    name: 'Kiwi de Verao',
    note: 'Kiwi, uva verde e hortela para um final frio.',
    ingredients: ['2 kiwis', '1 cacho pequeno de uva verde', '4 folhas de hortela', 'gelo'],
    method:
      'Bata o kiwi com a uva e acrescente a hortela no final. Sirva sem demora para manter a cor brilhante.',
    profile: 'Doce herbaceo e muito gelado.',
    bestMoment: 'Perfeito para tardes leves e encontros curtos.',
    pairing: 'Vai bem com mix de castanhas e queijo brie.',
    serve: '270 ml',
    tilt: -1.1,
  },
  {
    id: 'clorofila-tropical',
    category: 'verdes',
    name: 'Clorofila Tropical',
    note: 'Abacaxi, pepino, couve e manjericao fresco.',
    ingredients: ['1 fatia grande de abacaxi', 'meio pepino', '1 folha de couve', '3 folhas de manjericao'],
    method:
      'Bata todos os ingredientes com um pouco de agua gelada ate obter um verde luminoso e aromatico.',
    profile: 'Frutado com base vegetal elegante.',
    bestMoment: 'Excelente para almoco leve ou pos-praia.',
    pairing: 'Combina com sanduiche de mozzarella de bufala.',
    serve: '320 ml',
    tilt: 1.6,
  },
  {
    id: 'pepino-refrescante',
    category: 'verdes',
    name: 'Pepino Refrescante',
    note: 'Pepino, pera, limao siciliano e folhas frias.',
    ingredients: ['meio pepino', '1 pera madura', 'suco de meio limao siciliano', 'folhas de hortela'],
    method:
      'Bata a pera com o pepino, ajuste com o limao e finalize com hortela em pulsos curtos.',
    profile: 'Aquoso, elegante e pouco doce.',
    bestMoment: 'Serve muito bem em dias mais abafados.',
    pairing: 'Fica bonito ao lado de salada caprese.',
    serve: '280 ml',
    tilt: -1.4,
  },
  {
    id: 'uva-verde-com-hortela',
    category: 'verdes',
    name: 'Uva Verde com Hortela',
    note: 'Uva verde, maca clara e um brilho de limao.',
    ingredients: ['1 xicara de uva verde', 'meia maca verde', 'suco de meio limao', '5 folhas de hortela'],
    method:
      'Bata tudo com gelo ate que a espuma fique fina. Sirva em copo pequeno para preservar o frescor.',
    profile: 'Suculento com perfume limpo.',
    bestMoment: 'Funciona muito bem como aperitivo sem alcool.',
    pairing: 'Combina com bruschetta de tomate assado.',
    serve: '260 ml',
    tilt: 1.05,
  },
  {
    id: 'manga-nuvem',
    category: 'tropicais',
    name: 'Manga Nuvem',
    note: 'Manga palmer, coco e um toque leve de baunilha natural.',
    ingredients: ['1 manga madura', '180 ml de agua de coco', '2 colheres de coco fresco', '1 gota de baunilha'],
    method:
      'Bata a manga com a agua de coco e o coco. Use a baunilha apenas para arredondar o aroma.',
    profile: 'Cremoso, solar e muito macio.',
    bestMoment: 'Excelente para um fim de tarde lento.',
    pairing: 'Vai muito bem com bolo de coco ou tapioca amanteigada.',
    serve: '320 ml',
    tilt: -1.25,
  },
  {
    id: 'goiaba-solar',
    category: 'tropicais',
    name: 'Goiaba Solar',
    note: 'Goiaba vermelha, laranja e gelo lapidado.',
    ingredients: ['1 goiaba vermelha', '150 ml de suco de laranja', 'agua gelada', 'gelo'],
    method:
      'Bata a goiaba ate ficar lisa, adicione o suco de laranja e ajuste a textura com um pouco de agua gelada.',
    profile: 'Perfume marcante e final aveludado.',
    bestMoment: 'Funciona bem em brunch tropical ou cafe da tarde.',
    pairing: 'Combina com queijo minas padrao e pao doce leve.',
    serve: '300 ml',
    tilt: 1.1,
  },
  {
    id: 'caju-cremoso',
    category: 'tropicais',
    name: 'Caju Cremoso',
    note: 'Caju fresco, manga e agua de coco clara.',
    ingredients: ['2 cajus', 'meia manga', '160 ml de agua de coco', 'gelo a gosto'],
    method:
      'Bata tudo ate obter um suco denso e brilhante. Sirva imediatamente para manter o aroma fresco do caju.',
    profile: 'Tropical, sedoso e ligeiramente floral.',
    bestMoment: 'Muito bom para o meio da tarde.',
    pairing: 'Vai bem com biscoito de polvilho e queijo coalho.',
    serve: '310 ml',
    tilt: -1.55,
  },
  {
    id: 'papaya-com-gengibre',
    category: 'tropicais',
    name: 'Papaya com Gengibre',
    note: 'Mamao formosa, laranja e um corte de gengibre.',
    ingredients: ['1 xicara de mamao', '120 ml de suco de laranja', '1 fatia fina de gengibre', 'gelo'],
    method:
      'Bata o mamao com o suco de laranja e use o gengibre apenas para alongar o final, sem dominar o copo.',
    profile: 'Doce redondo com calor discreto.',
    bestMoment: 'Perfeito para manhas lentas ou pos-treino leve.',
    pairing: 'Combina com granola tostada e iogurte.',
    serve: '300 ml',
    tilt: 1.4,
  },
  {
    id: 'abacaxi-aveludado',
    category: 'tropicais',
    name: 'Abacaxi Aveludado',
    note: 'Abacaxi, maracuja e coco em textura cremosa.',
    ingredients: ['2 fatias de abacaxi', 'polpa de 1 maracuja', '2 colheres de coco fresco', 'agua gelada'],
    method:
      'Bata tudo ate que o copo fique espesso, mas ainda brilhante. Se quiser mais leve, acrescente um pouco mais de agua.',
    profile: 'Tropical intenso com final macio.',
    bestMoment: 'Faz bonito em encontros de fim de tarde.',
    pairing: 'Vai bem com sanduiche de frango grelhado e ervas.',
    serve: '320 ml',
    tilt: -1.15,
  },
  {
    id: 'rosa-de-melancia',
    category: 'roses',
    name: 'Rosa de Melancia',
    note: 'Melancia, limao e folhas pequenas de hortela.',
    ingredients: ['2 xicaras de melancia', 'suco de meio limao', '4 folhas de hortela', 'gelo'],
    method:
      'Bata a melancia com o limao e deixe a hortela apenas perfumar no final. Sirva bem gelado.',
    profile: 'Aquoso, doce e delicadamente aromatico.',
    bestMoment: 'Perfeito para tardes muito quentes.',
    pairing: 'Combina com salada grega ou queijo feta.',
    serve: '320 ml',
    tilt: 1.3,
  },
  {
    id: 'pitaya-fresca',
    category: 'roses',
    name: 'Pitaya Fresca',
    note: 'Pitaya rosa, agua de coco e lima espremida.',
    ingredients: ['1 pitaya rosa', '180 ml de agua de coco', 'suco de meia lima', 'gelo'],
    method:
      'Bata tudo ate obter uma cor uniforme. Sirva em copo transparente para valorizar o tom.',
    profile: 'Suave, luminosa e cenica.',
    bestMoment: 'Fica linda em mesas de brunch e eventos diurnos.',
    pairing: 'Vai bem com crostini de ricota e mel.',
    serve: '290 ml',
    tilt: -1.3,
  },
  {
    id: 'morango-da-serra',
    category: 'roses',
    name: 'Morango da Serra',
    note: 'Morango fresco, laranja-baia e um ponto de manjericao.',
    ingredients: ['1 xicara de morangos', '120 ml de suco de laranja-baia', '2 folhas de manjericao', 'gelo'],
    method:
      'Bata o morango com a laranja e use o manjericao somente no final para deixar o aroma mais limpo.',
    profile: 'Frutado, redondo e perfumado.',
    bestMoment: 'Excelente para cafe da tarde e mesas delicadas.',
    pairing: 'Combina com mille-feuille simples ou biscoito amanteigado.',
    serve: '280 ml',
    tilt: 1.55,
  },
  {
    id: 'hibisco-com-caju',
    category: 'roses',
    name: 'Hibisco com Caju',
    note: 'Infusao fria de hibisco, caju e limao pequeno.',
    ingredients: ['150 ml de hibisco frio', '1 caju', 'suco de meio limao', 'gelo quebrado'],
    method:
      'Bata o hibisco com o caju e ajuste com limao. O resultado fica perfumado e ligeiramente floral.',
    profile: 'Aromatico, fresco e com cor intensa.',
    bestMoment: 'Brilha em fins de tarde mais longos.',
    pairing: 'Vai bem com castanhas tostadas e queijo de cabra.',
    serve: '300 ml',
    tilt: -1.05,
  },
  {
    id: 'beterraba-rose',
    category: 'roses',
    name: 'Beterraba Rose',
    note: 'Beterraba assada, maca vermelha e laranja suave.',
    ingredients: ['2 fatias finas de beterraba assada', '1 maca vermelha', '100 ml de suco de laranja', 'gelo'],
    method:
      'Bata tudo ate a textura ficar lisa e brilhante. A beterraba assada deixa o sabor mais doce e elegante.',
    profile: 'Terroso delicado com final doce e limpo.',
    bestMoment: 'Funciona como assinatura do menu para ocasioes especiais.',
    pairing: 'Combina com sanduiche aberto de queijo de cabra.',
    serve: '300 ml',
    tilt: 1.15,
  },
]
